name: commute_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # State & UI
  intl: ^0.19.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # Background Service & Notifications
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.1.2 # Required for creating notification channel

  # Location & Maps
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  http: ^1.2.1
  google_polyline_algorithm: ^3.1.0
  
  # Utility
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  csv: ^6.0.0
  fl_chart: ^0.68.0
  share_plus: ^9.0.0
  uuid: ^4.4.0
  shared_preferences: ^2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon1.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/

